name: upower
version: 1.90.0
summary: An abstraction for power devices
description: |
    UPower is an abstraction for enumerating power devices, listening
    to device events and querying history and statistics.
confinement: strict
base: core22

slots:
  upower-dbus:
    interface: dbus
    bus: system
    name: org.freedesktop.UPower

  upower:
    interface: upower-observe

plugs:
  upower-client:
    interface: upower-observe

apps:
  upowerd:
    command: usr/libexec/upowerd
    daemon: dbus
    daemon-scope: system
    activates-on:
      - upower-dbus
    slots:
      - upower
    plugs:
      - hardware-observe
      - bluez

  upower:
    command: usr/bin/upower
    plugs:
      - upower-client

layout:
  /etc/UPower:
    bind: $SNAP/etc/UPower

parts:
  upower:
    build-packages:
    - meson
    - libglib2.0-dev
    - xsltproc
    - libgudev-1.0-dev
    - gtk-doc-tools
    stage-packages:
    - libgudev-1.0-0
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    source-type: tar
    source: https://gitlab.freedesktop.org/upower/upower/-/archive/v1.90.0/upower-v1.90.0.tar.bz2
