name: upower
version: 1.90.0
summary: An abstraction for power devices
description: |
    UPower is an abstraction for enumerating power devices, listening
    to device events and querying history and statistics.
confinement: strict
base: core22

slots:
  upower-dbus:
    interface: dbus
    bus: system
    name: org.freedesktop.UPower

  upower:
    interface: upower-observe

plugs:
  upower-client:
    interface: upower-observe

apps:
  upowerd:
    command: usr/libexec/upowerd
    daemon: dbus
    daemon-scope: system
    activates-on:
      - upower-dbus
    slots:
      - upower
    plugs:
      - hardware-observe

  upower:
    command: usr/bin/upower
    plugs:
      - upower-client

layout:
  /etc/UPower:
    bind: $SNAP/etc/UPower

parts:
  meson-deps:
    plugin: python
    source: https://github.com/mesonbuild/meson/releases/download/0.63.0/meson-0.63.0.tar.gz
    build-packages:
      - ninja-build
      - python3-distutils-extra
    prime:
      - -bin
      - -etc
      - -lib
      - -share
      - -usr

  upower:
    after:
      - meson-deps
    build-packages:
    - libglib2.0-dev
    - xsltproc
    - libgudev-1.0-dev
    - gtk-doc-tools
    stage-packages:
    - libgudev-1.0-0
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    source-type: tar
    source: https://gitlab.freedesktop.org/upower/upower/-/archive/v1.90.0/upower-v1.90.0.tar.bz2
